# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader:
        include_format: false
    view:
        view_response_listener:  true
#        formats:
#            rss: true
#            xml: false
#        templating_formats:
#            html: true
#        force_redirects:
#            html: true
#        failed_validation: HTTP_BAD_REQUEST
#        default_engine: twig
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
#            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html ] }
            - { path: ^/, stop: true }