# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /
    controller: App\Controller\Admin\UserController::index
    defaults:
        template: security/login.html.twig
        page: 1

users:
    type:     rest
    resource: App\Controller\Api\UserController
    prefix:   /api
